server:
  port: 9002
spring:
  application:
    name: zxl-service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.6:3306/zxl_exchange_user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: cancan
    password: uURUx%7i
  redis:
    host: 118.126.92.128
    port: 6379
    password:
  rabbitmq:
    host: 118.126.92.128
    username: guest
    password: 123456

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

jwt:
  config:
    key: whoiszxl
    ttl: 360000

msg:
  mock: true