server:
  port: 9005
spring:
  application:
    name: zxl-service-wallet
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.126.92.128:13301/zxl_exchange_wallet?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  redis:
    host: 118.126.92.128
  rabbitmq:
    host: 118.126.92.128
    username: guest
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://118.126.92.128:8761/eureka/
  instance:
    prefer-ip-address: false

jwt:
  config:
    key: whoiszxl
    ttl: 36000000

feign:
  hystrix:
    enabled: true
